BASE_URL = "http://api.shopstyle.com/api/v2/"
PID = "uid900-25284470-95"
FILTERS = ["Price", "Color", "Discount", "Brand", "Retailer", "Size", "Category"]
MAX_RESULTS_PER_PAGE = 50
MAX_OFFSET = 5000
MAX_SET_SIZE = MAX_OFFSET + MAX_RESULTS_PER_PAGE

shopstyle_relevant_items_Female = ['womens-clothes', 'womens-suits', 'shorts', 'blazers', 'tees-and-tshirts',
                                   'jeans', 'bootcut-jeans', 'classic-jeans', 'cropped-jeans', 'distressed-jeans',
                                   'flare-jeans', 'relaxed-jeans', 'skinny-jeans', 'straight-leg-jeans',
                                   'stretch-jeans', 'womens-tops', 'button-front-tops', 'camisole-tops',
                                   'cashmere-tops', 'halter-tops', 'longsleeve-tops', 'shortsleeve-tops',
                                   'sleeveless-tops', 'tank-tops', 'tunic-tops', 'polo-tops', 'skirts', 'mini-skirts',
                                   'mid-length-skirts', 'long-skirts', 'sweaters', 'sweatshirts', 'cashmere-sweaters',
                                   'cardigan-sweaters', 'crewneck-sweaters', 'turleneck-sweaters', 'v-neck-sweaters',
                                   'belts' 'chinos-and-khakis', 'womens-pants', 'wide-leg-pants', 'skinny-pants',
                                   'dress-pants', 'cropped-pants', 'casual-pants', 'dresses', 'cocktail-dresses',
                                   'day-dresses', 'evening-dresses', 'jackets', 'casual-jackets', 'leather-jackets',
                                   'vests', 'coats', 'womens-outerwear', 'fur-and-shearling-coats',
                                   'leather-and-suede-coats', 'puffer-coats', 'raincoats-and-trenchcoats', 'wool-coats',
                                   'leggings', 'tights']

shopstyle_relevant_items_Male = ['mens-clothes', 'mens-belts', 'mens-jackets', 'mens-denim-jacket',
                                 'mens-jeans', 'mens-bootcut-jeans', 'mens-low-rise-jeans', 'mens-distressed-jeans',
                                 'mens-slim-jeans', 'mens-relaxed-jeans', 'mens-loose-jeans', 'mens-straight-leg-jeans',
                                 'mens-leather-and-suede-coats', 'mens-overcoats-and-trenchcoats', 'mens-wool-coats',
                                 'mens-pants', 'mens-cargo-pants', 'mens-casual-pants', 'mens-chinos-and-khakis',
                                 'mens-shirts', 'mens-dress-shirts', 'mens-longsleeve-shirts', 'mens-cardigan-sweaters',
                                 'mens-polo-shirts', 'mens-tees-and-tshirts', 'mens-shorts', 'mens-shortsleeve-shirts',
                                 'mens-sweaters', 'mens-sweatshirts', 'mens-cashmere-sweaters',
                                 'mens-crewneck-sweaters', 'mens-turleneck-sweaters', 'mens-v-neck-sweaters',
                                 'mens-half-zip-sweaters', 'mens-vests', 'mens-suits', 'mens-dress-pants',]

shopstyle_paperdoll_female = {'belts': 'belt',
                             'bootcut-jeans': 'jeans',
                             'classic-jeans': 'jeans',
                             'cropped-jeans': 'jeans',
                             'distressed-jeans': 'jeans',
                             'flare-jeans': 'jeans',
                             'relaxed-jeans': 'jeans',
                             'skinny-jeans': 'jeans',
                             'straight-leg-jeans': 'jeans',
                             'stretch-jeans': 'jeans',
                             'jeans': 'jeans',
                             'womens-suits': 'suit',
                             'shorts': 'shorts',
                             'blazers': 'blazer',
                             'tees-and-tshirts': 't-shirt',
                             'womens-tops': 'top',
                             'button-front-tops': 'top',
                             'camisole-tops': 'top',
                             'cashmere-tops': 'top',
                             'halter-tops': 'top',
                             'longsleeve-tops': 'top',
                             'shortsleeve-tops': 'shirt',
                             'sleeveless-tops': 'top',
                             'tank-tops': 'top',
                             'tunic-tops': 'blouse',
                             'polo-tops': 'top',
                             'skirts': 'skirt',
                             'mini-skirts': 'skirt',
                             'mid-length-skirts': 'skirt',
                             'long-skirts': 'skirt',
                             'sweaters': 'sweater',
                             'sweatshirts': 'sweatshirt',
                             'cashmere-sweaters': 'sweater',
                             'cardigan-sweaters': 'cardigan',
                             'crewneck-sweaters': 'sweater',
                             'turleneck-sweaters': 'sweater',
                             'v-neck-sweaters': 'sweater',
                             'womens-pants': 'pants',
                             'wide-leg-pants': 'pants',
                             'skinny-pants': 'pants',
                             'dress-pants': 'pants',
                             'cropped-pants': 'pants',
                             'casual-pants': 'pants',
                             'dresses': 'dress',
                             'cocktail-dresses': 'dress',
                             'day-dresses': 'dress',
                             'evening-dresses': 'dress',
                             'jackets': 'jacket',
                             'neckless-jackets': 'jacket',
                             'casual-jackets': 'jacket',
                             'leather-jackets': 'jacket',
                             'vests': 'vest',
                             'coats': 'coat',
                             'womens-outerwear': 'coat',
                             'plus-size-outerwear': 'coat',
                             'fur-and-shearling-coats': 'coat',
                             'leather-and-suede-coats': 'coat',
                             'puffer-coats': 'coat',
                             'raincoats-and-trenchcoats': 'coat',
                             'wool-coats': 'coat',
                             'leggings': 'leggings',
                             'tights': 'tights'}

shopstyle_paperdoll_male = {'mens-belts' : 'belt',
                             'mens-jackets': 'jacket',
                             'mens-denim-jacket': 'jacket',
                             'mens-jeans': 'jeans',
                             'mens-bootcut-jeans': 'jeans',
                             'mens-low-rise-jeans': 'jeans',
                             'mens-distressed-jeans': 'jeans',
                             'mens-slim-jeans': 'jeans',
                             'mens-relaxed-jeans': 'jeans',
                             'mens-loose-jeans': 'jeans',
                             'mens-straight-leg-jeans': 'jeans',
                             'mens-leather-and-suede-coats': 'coat',
                             'mens-overcoats-and-trenchcoats': 'coat',
                             'mens-wool-coats' : 'coat',
                             'mens-pants' : 'pants',
                             'mens-cargo-pants' : 'pants',
                             'mens-casual-pants' :'pants',
                             'mens-chinos-and-khakis' : 'pants',
                             'mens-dress-pants' : 'pants',
                             'mens-shirts' : 'shirt',
                             'mens-dress-shirts' : 'shirt',
                             'mens-longsleeve-shirts' : 'shirt',
                             'mens-shortsleeve-shirts' : 'shirt',
                             'mens-polo-shirts' : 'shirt',
                             'mens-tees-and-tshirts' : 'shirt',
                             'mens-shorts' : 'shorts',
                             'mens-sweaters' : 'sweater',
                             'mens-sweatshirts' : 'sweatshirt',
                             'mens-cashmere-sweaters' : 'sweater',
                             'mens-cardigan-sweaters' : 'sweater',
                             'mens-crewneck-sweaters' : 'sweater',
                             'mens-turleneck-sweaters' : 'sweater',
                             'mens-v-neck-sweaters' : 'sweater',
                             'mens-half-zip-sweaters': 'sweater',
                             'mens-vests' : 'vest',
                             'mens-suits': 'suit'}


fat2paperdoll_Female = {
    'women': 'women',
    'womens-clothes': 'womens-clothes',
    'plus-sizes': 'plus-sizes',
    'plus-size-jeans': 'jeans',
    'plus-size-dresses': 'dress',
    'plus-size-jackets': 'jacket',
    'plus-size-outerwear': 'coat',
    'plus-size-pants': 'pants',
    'plus-size-shorts': 'shorts',
    'plus-size-skirts': 'skirt',
    'plus-size-sweatshirts': 'sweatshirt',
    'plus-size-sweaters': 'sweater',
    'plus-size-swimsuits': 'swimsuit',
    'plus-size-tops': 'top'}

fat2paperdoll_Male = {
    'men': 'men',
    'mens-clothes': 'mens-clothes',
    'mens-big-and-tall': 'plus-sizes',
    'mens-big-and-tall-coats-and-jackets': 'coat',
    'mens-big-and-tall-jeans': 'jeans',
    'mens-big-and-tall-blazers': 'coat',
    'mens-big-and-tall-pants': 'pants',
    'mens-big-and-tall-shorts': 'shorts',
    'mens-big-and-tall-sweaters': 'sweater',
    'mens-big-and-tall-suits': 'suit',
    'mens-big-and-tall-shirts': 'shirt'}

'''
this is a list of categories under womens-clothing and mens-clothing in case its needed
TOP LEVEL CLOTHES:
 u'womens-outerwear',
 u'shorts',
 u'jackets',

['womens-clothes',

 u'womens-outerwear',
 u'wool-coats',
 u'coats',
 u'puffer-coats',
 u'fur-and-shearling-coats',
 u'raincoats-and-trenchcoats',
 u'leather-and-suede-coats',

 u'jewelry',
 u'diamond-jewelry',
 u'diamond-necklaces',
 u'diamond-earrings',
 u'diamond-bracelets',
 u'diamond-rings',
 u'charms',
 u'necklaces',
 u'earrings',
 u'bracelets',
 u'brooches-and-pins',
 u'rings',
 u'watches',

 u'shorts',

 u'jackets',
 u'blazers',
 u'neckless-jackets',
 u'casual-jackets',
 u'vests',
 u'leather-jackets',

 u'skirts',
 u'mini-skirts',
 u'mid-length-skirts',
 u'long-skirts',

 u'womens-suits',

 u'jeans',
 u'classic-jeans',
 u'cropped-jeans',
 u'skinny-jeans',
 u'stretch-jeans',
 u'straight-leg-jeans',
 u'distressed-jeans',
 u'flare-jeans',
 u'bootcut-jeans',
 u'relaxed-jeans',

 u'womens-tops',
 u'tees-and-tshirts',
 u'cut-sew-tops',
 u'camisole-tops',
 u'button-front-tops',
 u'tank-tops',
 u'tunic-tops',
 u'sleeveless-tops',
 u'halter-tops',
 u'polo-tops',

 u'sweaters',
 u'v-neck-sweaters',
 u'cardigan-sweaters',
 u'crewneck-sweaters',
 u'turleneck-sweaters',
 u'ensembles',

 u'womens-pants',
 u'dress-pants',
 u'casual-pants',
 u'cropped-pants',
 u'skinny-pants',
 u'leggings',
 u'wide-leg-pants',

 u'sweatshirts',

#NOTE WOMENS ATHLETIC SEEMS TO HAVE GONE BYE-BYE
 u'womens-athletic-clothes',
 u'athletic-shorts',
 u'athletic-jackets',
 u'athletic-skirts',
 u'sports-bras-and-underwear',
 u'athletic-tops',
 u'athletic-pants',

#APPARENTLY THIS CATEGORY IS NO MORE
 u'bridal',
 u'bridesmaid',
 u'bridesmaid-jewelry',
 u'bridal-bridesmaid-dresses',
 u'bridesmaid-bags',
 u'bride',
 u'bridal-lingerie',
 u'bridal-gowns',
 u'bridal-shoes',
 u'bridal-jewelry',
 u'bridal-bags',
 u'bridal-veils',

#GONE WITH THE WIND
 u'maternity-clothes',
 u'maternity-outerwear',
 u'maternity-intimates',
 u'maternity-shorts',
 u'maternity-jackets',
 u'maternity-skirts',
 u'maternity-jeans',
 u'maternity-tops',
 u'maternity-sweaters',
 u'maternity-pants',
 u'maternity-dresses',
 u'maternity-swimsuits',

 u'dresses',
 u'bridal-dresses',
 u'bridesmaid-dresses',
 u'wedding-dresses',
 u'cocktail-dresses',
 u'evening-dresses',
 u'day-dresses',

 u'womens-intimates',
 u'undershirts',
 u'camisoles',
 u'panties',
 u'chemises',
 u'socks',
 u'hosiery',
 u'thongs',
 u'pajamas',
 u'bras',
 u'roomwear',
 u'slippers',
 u'robes',
 u'shapewear',

 u'plus-sizes',
 u'plus-size-outerwear',
 u'plus-size-shorts',
 u'plus-size-jackets',
 u'plus-size-skirts',
 u'plus-size-suits',
 u'plus-size-jeans',
 u'plus-size-tops',
 u'plus-size-sweaters',
 u'plus-size-pants',
 u'plus-size-sweatshirts',
 u'plus-size-dresses',
 u'plus-size-intimates',
 u'plus-size-swimsuits',

 u'petites',
 u'petite-outerwear',
 u'petite-shorts',
 u'petite-jackets',
 u'petite-skirts',
 u'petite-suits',
 u'petite-jeans',
 u'petite-tops',
 u'petite-sweaters',
 u'petite-pants',
 u'petite-sweatshirts',
 u'petite-dresses',
 u'petite-intimates',
 u'petite-swimsuits',

 u'womens-accessories',
 u'womens-eyewear',
 u'sunglasses',
 u'womens-eyeglasses',
 u'key-chains',
 u'gift-cards',
 u'straps',
 u'womens-tech-accessories',
 u'belts',
 u'scarves',
 u'womens-umbrellas',
 u'hats',
 u'gloves',

 u'swimsuits',
 u'one-piece-swimsuits',
 u'two-piece-swimsuits',
 u'swimsuit-coverups']

In [19]: get_all_subcategories(db.categories,'mens-clothes')
Out[19]:
['mens-clothes',
 u'mens-outerwear',
 u'mens-coats',
 u'mens-jackets',
 u'mens-denim-jackets',
 u'mens-overcoats-and-trenchcoats',
 u'mens-leather-and-suede-coats',
 u'mens-shorts',
 u'mens-sweatshirts',
 u'mens-suits',
 u'mens-jeans',
 u'mens-slim-jeans',
 u'mens-straight-leg-jeans',
 u'mens-distressed-jeans',
 u'mens-bootcut-jeans',
 u'mens-relaxed-jeans',
 u'mens-loose-jeans',
 u'mens-low-rise-jeans',
 u'mens-shirts',
 u'mens-tees-and-tshirts',
 u'mens-dress-shirts',
 u'mens-polo-shirts',
 u'mens-shortsleeve-shirts',
 u'mens-longsleeve-shirts',
 u'mens-sleepwear',
 u'mens-slippers',
 u'mens-pajamas',
 u'mens-robes',
 u'mens-sweaters',
 u'mens-v-neck-sweaters',
 u'mens-cardigan-sweaters',
 u'mens-crewneck-sweaters',
 u'mens-turtleneck-sweaters',
 u'mens-half-zip-sweaters',
 u'mens-vests',
 u'mens-ties',
 u'mens-pants',
 u'mens-casual-pants',
 u'mens-cargo-pants',
 u'mens-dress-pants',
 u'mens-chinos-and-khakis',
 u'mens-athletic',
 u'mens-athletic-shorts',
 u'mens-athletic-jackets',
 u'mens-athletic-shirts',
 u'mens-athletic-pants',
 u'mens-underwear-and-socks',
 u'mens-tee-shirts',
 u'mens-socks',
 u'mens-boxers',
 u'mens-briefs',
 u'mens-big-and-tall',
 u'mens-big-and-tall-coats-and-jackets',
 u'mens-big-and-tall-shorts',
 u'mens-big-and-tall-suits',
 u'mens-big-and-tall-jeans',
 u'mens-big-and-tall-shirts',
 u'mens-big-and-tall-sweaters',
 u'mens-big-and-tall-pants',
 u'mens-big-and-tall-underwear-and-socks',
 u'mens-accessories',
 u'mens-eyewear',
 u'mens-sunglasses',
 u'mens-eyeglasses',
 u'mens-tech-accessories',
 u'mens-belts',
 u'mens-umbrellas',
 u'mens-hats',
 u'mens-gloves-and-scarves',
 u'mens-wallets',
 u'mens-watches-and-jewelry',
 u'mens-jewelry',
 u'mens-cuff-links',
 u'mens-watches',
 u'mens-swimsuits']
'''
